name: Nightly Test Automation

on:
  repository_dispatch: # this will catch the trigger from repo A
    types: [run-automation]
  schedule:
    - cron: '0 1 * * *'  # Daily run at 1 AM UTC
  workflow_dispatch:     # Manual trigger option

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Compatible Chrome Version (v124)
        run: |
          sudo apt purge -y google-chrome-stable || true
          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_124.0.6367.91-1_amd64.deb
          sudo apt install -y ./google-chrome-stable_124.0.6367.91-1_amd64.deb

      - name: Run Tests using TestSuite.xml
        run: mvn clean test -DsuiteXmlFile=TestSuite.xml

      - name: Upload TestNG Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-report
          path: test-output/ExtentReport.html
